import { Check, Pencil, Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import Modal from '../components/Modal'
import { useFinance } from '../contexts/FinanceContext'
import type { Account, AccountKind, AccountStatus } from '../types'
import { brl, dueLabel, priorityClass, shortDate } from '../utils/format'

const initial={kind:'pagar' as AccountKind,name:'',description:'',category:'Outros',amount:'',dueDate:new Date().toISOString().slice(0,10),status:'pendente' as AccountStatus,paymentMethod:'PIX',notes:''}
export default function Accounts(){
 const {accounts,addAccount,updateAccount,removeAccount}=useFinance(); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Account|null>(null); const [form,setForm]=useState(initial); const [tab,setTab]=useState<AccountKind>('pagar')
 const list=accounts.filter(a=>a.kind===tab).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))
 const edit=(a:Account)=>{setEditing(a);setForm({kind:a.kind,name:a.name,description:a.description,category:a.category,amount:String(a.amount),dueDate:a.dueDate,status:a.status,paymentMethod:a.paymentMethod,notes:a.notes??''});setOpen(true)}
 const submit=(e:FormEvent)=>{e.preventDefault(); const payload={...form,amount:Number(form.amount)}; if(!payload.name||payload.amount<=0)return; if(editing)updateAccount({...payload,id:editing.id});else addAccount(payload);setOpen(false);setEditing(null);setForm(initial)}
 const settle=(a:Account)=>updateAccount({...a,status:a.kind==='pagar'?'pago':'recebido'})
 return <div className="page-stack"><div className="page-title"><div><span className="eyebrow">Compromissos</span><h1>Contas</h1><p>Veja vencimentos, prioridades e recebimentos previstos.</p></div><button className="primary-btn" onClick={()=>{setEditing(null);setForm({...initial,kind:tab,status:tab==='pagar'?'pendente':'previsto'});setOpen(true)}}><Plus size={17}/> Nova conta</button></div>
 <div className="tabs"><button className={tab==='pagar'?'active':''} onClick={()=>setTab('pagar')}>A pagar</button><button className={tab==='receber'?'active':''} onClick={()=>setTab('receber')}>A receber</button></div>
 <div className="accounts-grid">{list.map(a=><article className="account-card" key={a.id}><div className="account-top"><div className={`priority ${a.kind==='pagar'&&a.status!=='pago'?priorityClass(a.dueDate):'success'}`}><span/>{a.kind==='pagar'&&a.status!=='pago'?dueLabel(a.dueDate):a.status}</div><div className="row-actions"><button className="icon-btn" onClick={()=>edit(a)}><Pencil size={16}/></button><button className="icon-btn danger-text" onClick={()=>confirm('Excluir esta conta?')&&removeAccount(a.id)}><Trash2 size={16}/></button></div></div><h3>{a.name}</h3><p>{a.description}</p><strong className="account-value">{brl(a.amount)}</strong><div className="account-meta"><span>Vencimento</span><strong>{shortDate(a.dueDate)}</strong><span>Categoria</span><strong>{a.category}</strong></div>{!['pago','recebido'].includes(a.status)&&<button className="secondary-btn full" onClick={()=>settle(a)}><Check size={16}/> {a.kind==='pagar'?'Marcar como paga':'Marcar como recebida'}</button>}</article>)}</div>
 {open&&<Modal title={editing?'Editar conta':'Nova conta'} onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={submit}><label>Tipo<select value={form.kind} onChange={e=>{const k=e.target.value as AccountKind;setForm({...form,kind:k,status:k==='pagar'?'pendente':'previsto'})}}><option value="pagar">A pagar</option><option value="receber">A receber</option></select></label><label>Valor<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label className="span-2">Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Categoria<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Vencimento<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Forma<input value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as AccountStatus})}>{form.kind==='pagar'?<><option value="pendente">Pendente</option><option value="pago">Pago</option><option value="atrasado">Atrasado</option></>:<><option value="previsto">Previsto</option><option value="recebido">Recebido</option><option value="atrasado">Atrasado</option></>}</select></label><label className="span-2">Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-actions span-2"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-btn">Salvar</button></div></form></Modal>}
 </div>
}
