import { Pencil, Plus, Target, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import Modal from '../components/Modal'
import { useFinance } from '../contexts/FinanceContext'
import type { Goal } from '../types'
import { brl, shortDate } from '../utils/format'
const initial={name:'',description:'',targetAmount:'',savedAmount:'0',monthlyAmount:'',targetDate:new Date(Date.now()+180*86400000).toISOString().slice(0,10)}
export default function Planning(){
 const {goals,addGoal,updateGoal,removeGoal}=useFinance(); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Goal|null>(null); const [form,setForm]=useState(initial)
 const edit=(g:Goal)=>{setEditing(g);setForm({name:g.name,description:g.description,targetAmount:String(g.targetAmount),savedAmount:String(g.savedAmount),monthlyAmount:String(g.monthlyAmount),targetDate:g.targetDate});setOpen(true)}
 const submit=(e:FormEvent)=>{e.preventDefault();const payload={...form,targetAmount:Number(form.targetAmount),savedAmount:Number(form.savedAmount),monthlyAmount:Number(form.monthlyAmount)};if(!payload.name||payload.targetAmount<=0)return;if(editing)updateGoal({...payload,id:editing.id});else addGoal(payload);setOpen(false);setEditing(null);setForm(initial)}
 return <div className="page-stack"><div className="page-title"><div><span className="eyebrow">Objetivos</span><h1>Planejamento</h1><p>Transforme metas em valores e prazos claros.</p></div><button className="primary-btn" onClick={()=>{setEditing(null);setForm(initial);setOpen(true)}}><Plus size={17}/> Nova meta</button></div>
 <div className="goals-grid">{goals.map(g=>{const pct=Math.min(100,(g.savedAmount/g.targetAmount)*100);const remaining=Math.max(0,g.targetAmount-g.savedAmount);const months=g.monthlyAmount>0?Math.ceil(remaining/g.monthlyAmount):null;return <article className="goal-card" key={g.id}><div className="goal-icon"><Target/></div><div className="row-actions goal-actions"><button className="icon-btn" onClick={()=>edit(g)}><Pencil size={16}/></button><button className="icon-btn danger-text" onClick={()=>confirm('Excluir esta meta?')&&removeGoal(g.id)}><Trash2 size={16}/></button></div><h3>{g.name}</h3><p>{g.description}</p><div className="goal-values"><div><span>Guardado</span><strong>{brl(g.savedAmount)}</strong></div><div><span>Objetivo</span><strong>{brl(g.targetAmount)}</strong></div></div><div className="progress large"><i style={{width:`${pct}%`}}/></div><div className="goal-foot"><span>{pct.toFixed(0)}% concluído</span><span>{months?`~${months} meses restantes`:`Meta até ${shortDate(g.targetDate)}`}</span></div></article>})}</div>
 {open&&<Modal title={editing?'Editar meta':'Nova meta'} onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={submit}><label className="span-2">Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="span-2">Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Valor objetivo<input type="number" min="0" step="0.01" value={form.targetAmount} onChange={e=>setForm({...form,targetAmount:e.target.value})}/></label><label>Já reservado<input type="number" min="0" step="0.01" value={form.savedAmount} onChange={e=>setForm({...form,savedAmount:e.target.value})}/></label><label>Guardar por mês<input type="number" min="0" step="0.01" value={form.monthlyAmount} onChange={e=>setForm({...form,monthlyAmount:e.target.value})}/></label><label>Data objetivo<input type="date" value={form.targetDate} onChange={e=>setForm({...form,targetDate:e.target.value})}/></label><div className="form-actions span-2"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-btn">Salvar</button></div></form></Modal>}
 </div>
}
