import { Download, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import EmptyState from '../components/EmptyState'
import Modal from '../components/Modal'
import { useFinance } from '../contexts/FinanceContext'
import type { Transaction, TransactionType } from '../types'
import { exportTransactionsXlsx } from '../utils/exportToExcel'
import { brl, shortDate } from '../utils/format'

const categories = ['Alimentação','Transporte','Moradia','Saúde','Educação','Lazer','Assinaturas','Serviços','Investimentos','Salário','Vendas','Outros']
const initial = { type:'despesa' as TransactionType, description:'', category:'Outros', amount:'', date:new Date().toISOString().slice(0,10), paymentMethod:'PIX', status:'confirmado' as const, notes:'' }

export default function Transactions() {
  const { transactions, addTransaction, updateTransaction, removeTransaction } = useFinance()
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Transaction|null>(null); const [form,setForm]=useState(initial); const [query,setQuery]=useState(''); const [type,setType]=useState<'todos'|TransactionType>('todos')
  const filtered = useMemo(()=>transactions.filter(t=>(type==='todos'||t.type===type) && `${t.description} ${t.category}`.toLowerCase().includes(query.toLowerCase())),[transactions,type,query])
  const edit=(t:Transaction)=>{setEditing(t);setForm({type:t.type,description:t.description,category:t.category,amount:String(t.amount),date:t.date,paymentMethod:t.paymentMethod,status:t.status,notes:t.notes??''});setOpen(true)}
  const submit=(e:FormEvent)=>{e.preventDefault(); const payload={...form,amount:Number(form.amount)}; if(!payload.description||payload.amount<=0)return; if(editing) updateTransaction({...payload,id:editing.id}); else addTransaction(payload); setOpen(false);setEditing(null);setForm(initial)}
  return <div className="page-stack"><div className="page-title"><div><span className="eyebrow">Movimentações</span><h1>Transações</h1><p>Registre e acompanhe entradas e saídas.</p></div><div className="actions"><button className="secondary-btn" onClick={()=>void exportTransactionsXlsx(filtered)}><Download size={17}/> Exportar XLSX</button><button className="primary-btn" onClick={()=>{setEditing(null);setForm(initial);setOpen(true)}}><Plus size={17}/> Nova transação</button></div></div>
  <div className="toolbar"><div className="input-icon search"><Search size={17}/><input placeholder="Buscar por descrição ou categoria" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="todos">Todos os tipos</option><option value="receita">Receitas</option><option value="despesa">Despesas</option></select></div>
  <div className="panel table-panel">{filtered.length===0?<EmptyState/>:<div className="table-wrap"><table><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Tipo</th><th>Forma</th><th>Valor</th><th></th></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td>{shortDate(t.date)}</td><td><strong>{t.description}</strong></td><td>{t.category}</td><td><span className={`badge ${t.type}`}>{t.type}</span></td><td>{t.paymentMethod}</td><td className={t.type==='receita'?'positive':'negative'}>{t.type==='receita'?'+':'-'} {brl(t.amount)}</td><td><div className="row-actions"><button className="icon-btn" onClick={()=>edit(t)}><Pencil size={16}/></button><button className="icon-btn danger-text" onClick={()=>confirm('Excluir esta transação?')&&removeTransaction(t.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}</div>
  {open&&<Modal title={editing?'Editar transação':'Nova transação'} onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={submit}><label>Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as TransactionType})}><option value="receita">Receita</option><option value="despesa">Despesa</option></select></label><label>Valor<input type="number" step="0.01" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label><label className="span-2">Descrição<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><label>Categoria<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Data<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Forma de pagamento<input value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as 'confirmado'|'pendente'})}><option value="confirmado">Confirmado</option><option value="pendente">Pendente</option></select></label><label className="span-2">Observação<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions span-2"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-btn">Salvar</button></div></form></Modal>}
  </div>
}
